src/main/java/com/comarch/egeria/pp/srodkiTrwale/ListaSrodkowTrwalychPrcBean.java
package com.comarch.egeria.pp.srodkiTrwale;

import com.comarch.egeria.pp.data.DataRow;
import com.comarch.egeria.pp.data.JdbcUtils;
import com.comarch.egeria.pp.data.SqlBean;
import com.comarch.egeria.pp.data.SqlDataSelectionsHandler;
import com.comarch.egeria.web.User;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.context.annotation.Scope;

import javax.inject.Named;
import java.io.Serializable;
import java.sql.Connection;
import java.util.List;

@Scope("view")
@Named
public class ListaSrodkowTrwalychPrcBean extends SqlBean implements Serializable {
	private static final Logger log = LogManager.getLogger();



	public SqlDataSelectionsHandler getPplSrodkiTrwale(){
		return this.getLW("PPL_SRODKI_TRWALE");
	}

	public  SqlDataSelectionsHandler getPplPracownicy(){
        return this.getLW("PPL_PRACOWNICY");
    }

	public void generujWnioskiOZmianePracownika(DataRow rNaPrc){
	    if (rNaPrc==null) return;
		String info = "";

		SqlDataSelectionsHandler lw = this.getPplSrodkiTrwale();
		List<DataRow> selectedRows = lw.getSelectedRows();
		if (selectedRows.isEmpty()){
			User.warn("Nie zaznaczono żadnego wiersza.");
			return;
		}

		try(Connection conn = JdbcUtils.getConnection()){
			for (DataRow rStPodz: selectedRows) {
                String ret = JdbcUtils.sqlFnVarchar(conn, "ppadm.st_wniosek_zm_os_odp",  rStPodz.get("ps_id"), rNaPrc.getIdAsString());

                if (ret!=null && !ret.startsWith("000000"))
                    User.alert(ret);
				else {
					String wnNr = ""+JdbcUtils.sqlExecScalarQuery(conn, "select wn_numer from stt_wnioski where wn_id = ? ", ret);
					info += String.format("\r\n\r\nwniosek nr: %1$s \r\nnr inw.: %2$s; \r\nnazwa: %3$s", wnNr, rStPodz.get("sdn_numer_inw"), rStPodz.get("sdn_nazwa"));
				}
            }

			if (!info.isEmpty()){
				User.info("Wygenerowano wnioski o zmianę osoby odpowiedzialnej dla ST: " + info);
			}

			lw.clearSelection();
			lw.resetTs();

		} catch (Exception e) {
			log.error(e.getMessage(), e);
			User.alert(e);
		}
	}

	public void generujWnioskiOLikwidacje(){

		String info = "";

		SqlDataSelectionsHandler lw = this.getPplSrodkiTrwale();
		List<DataRow> selectedRows = lw.getSelectedRows();
		if (selectedRows.isEmpty()){
			User.warn("Nie zaznaczono żadnego wiersza.");
			return;
		}

		try(Connection conn = JdbcUtils.getConnection()){
			for (DataRow rStPodz: selectedRows) {
				String ret = JdbcUtils.sqlFnVarchar(conn, "ppadm.st_wniosek_likw", rStPodz.get("sdn_id"));

				if (ret!=null && !ret.startsWith("000000"))
					User.alert(ret);
				else {
					String wnNr = ""+JdbcUtils.sqlExecScalarQuery(conn, "select wn_numer from stt_wnioski where wn_id = ? ", ret);
					info += String.format("\r\n\r\nwniosek nr: %1$s \r\nnr inw.: %2$s; \r\nnazwa: %3$s", wnNr, rStPodz.get("sdn_numer_inw"), rStPodz.get("sdn_nazwa"));
				}
			}

			if (!info.isEmpty()){
				User.info("Wygenerowano wnioski o likwidację dla ST: " + info);
			}

			lw.clearSelection();
			lw.resetTs();

		} catch (Exception e) {
			log.error(e.getMessage(), e);
			User.alert(e);
		}
	}
}

src/main/java/com/comarch/egeria/pp/srodkiTrwale/ListaWnioskowStPrcBean.java
package com.comarch.egeria.pp.srodkiTrwale;

import com.comarch.egeria.pp.data.DataRow;
import com.comarch.egeria.pp.data.JdbcUtils;
import com.comarch.egeria.pp.data.SqlBean;
import com.comarch.egeria.pp.data.SqlDataSelectionsHandler;
import com.comarch.egeria.web.User;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.context.annotation.Scope;

import javax.inject.Named;
import java.io.Serializable;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

@Scope("view")
@Named
public class ListaWnioskowStPrcBean extends SqlBean implements Serializable {
	private static final Logger log = LogManager.getLogger();



	public SqlDataSelectionsHandler getPplSrodkiTrwale(){
		return this.getLW("PPL_SRODKI_TRWALE");
	}

	public SqlDataSelectionsHandler getPplSrodkiTrwaleWnioski(){
		return this.getLW("PPL_SRODKI_TRWALE_WNIOSKI");
	}

	public  SqlDataSelectionsHandler getPplPracownicy(){
        return this.getLW("PPL_PRACOWNICY");
    }


	public void zatwierdzWybraneWnioski(){

		SqlDataSelectionsHandler lw = this.getPplSrodkiTrwaleWnioski();
		List<DataRow> selectedRows = lw.getSelectedRows();

		try(Connection conn = JdbcUtils.getConnection()){

			String info = "";
			for (DataRow r : selectedRows) {

				Object wnNumer = r.get("wn_numer");
				Object wnpKod = r.get("wnp_kod");


				if (eq("T", r.get("wn_f_anulowany"))){
					User.alert("Brak możliwości zatwierdzenia wniosku '%1$s'. Wniosek ten został wcześniej anulowany.", wnNumer);
					continue;
				}

				if (eq("T", r.get("wn_f_zatwierdzony"))){
					User.alert("Brak możliwości zatwierdzenia wniosku '%1$s'. Wniosek ten został wcześniej zatwierdzony.", wnNumer);
					continue;
				}

				User user = User.getCurrentUser();
				if (eq("ZM_OS_ODP", wnpKod) && !eq(""+user.getPrcIdLong(), ""+r.get("wnp_wartosc_na"))){

//					User.alert("Wniosek o zmianę pracownika '%1$s' powinien zostać zatwierdzony przez pracownika, który ma go przyjąć (%2$s).", wnNumer, r.get("wnp_na_prc_info"));
//					continue;

					DataRow rPodwl = this.getLW("PPL_ZALOGOWANY_PODLAWDNI").find(r.get("wnp_wartosc_na"));
					if (
							(rPodwl == null ||	rPodwl.getAsLong("PRZ_POZIOM")==0L)//zalogowany nie jest przelozonym
							&& !user.hasPermission("PP_ST_ADMINISTRATOR") && !user.hasPermission("PP_ADMINISTRATOR")
					){
						User.alert("Wniosek '%1$s' o zmianę pracownika powinien zostać zatwierdzony przez przełożonego pracownika, który ma go przyjąć (%2$s), albo przez administratora ST (wymagana f.u.: PP_ST_ADMINISTRATOR lub PP_ADMINISTRATOR).",
								wnNumer, r.get("wnp_na_prc_info"));
						continue;
					}
				}

				if (eq("LIKW",wnpKod)){
					DataRow rPodwl = this.getLW("PPL_ZALOGOWANY_PODLAWDNI").find(r.get("WN_PRC_ID"));
					if (
							(rPodwl == null ||	rPodwl.getAsLong("PRZ_POZIOM")==0L)//zalogowany nie jest przelozonym
									&& !user.hasPermission("PP_ST_ADMINISTRATOR") && !user.hasPermission("PP_ADMINISTRATOR")
					){
						User.alert("Wniosek '%1$s' o likwidację powinien zostać zatwierdzony przez przełożonego pracownika, który go utworzył (%2$s), albo przez administratora ST (wymagana f.u.: PP_ST_ADMINISTRATOR lub PP_ADMINISTRATOR).",
								wnNumer, r.get("wn_prc_info"));
						continue;
					}

				}


				JdbcUtils.sqlExecNoQuery(conn, "update stt_wnioski set wn_f_zatwierdzony = 'T' where wn_id = ? ", r.get("wn_id"));
                JdbcUtils.sqlSPCall(conn,"ppadm.st_wniosek_wiadomosci",  r.get("wn_id"), "Środki trwałe / lista wniosków: zatwierdzono wniosek " + wnNumer);
				info += String.format("\r\n\r\nwn. nr <strong><b>%1$s</b></strong>\r\nnr inw.: %2$s \r\nnazwa: %3$s",
						r.get("wn_numer"),	 r.get("sdn_numer_inw"), r.get("sdn_nazwa"));
			}

			if (!info.isEmpty()){
				User.info("Zatwierdzono: " + info);
			}

			lw.clearSelection();
			lw.resetTs();

		} catch (Exception e) {
			log.error(e.getMessage(), e);
			User.alert(e);

		}

	}



	public void anulujWybraneWnioski(){

		SqlDataSelectionsHandler lw = this.getPplSrodkiTrwaleWnioski();
		List<DataRow> selectedRows = lw.getSelectedRows();

		try(Connection conn = JdbcUtils.getConnection()){

			String info = "";
			for (DataRow r : selectedRows) {

				Object wnNumer = r.get("wn_numer");

				if (eq("T", r.get("wn_f_anulowany"))){
					User.alert("Brak możliwości anulowania wniosku '%1$s'. Wniosek ten został wcześniej anulowany.", wnNumer);
					continue;
				}

				if (eq("T",r.get("wn_f_zatwierdzony"))){
					User.alert("Brak możliwości anulowania wniosku '%1$s'. Wniosek ten został wcześniej zatwierdzony.", wnNumer);
					continue;
				}

				if (eq("T", r.get("wn_f_dok_wygenerowano"))){
					User.alert("Brak możliwości anulowania wniosku '%1$s'. Dla tego wniosku wygenerowano dokumenty.", wnNumer);
					continue;
				}

				JdbcUtils.sqlExecNoQuery(conn, "update stt_wnioski set wn_f_anulowany = 'T' where wn_id = ? ", r.get("wn_id"));
				JdbcUtils.sqlSPCall(conn,"ppadm.st_wniosek_wiadomosci",  r.get("wn_id"), "Środki trwałe / lista wniosków: anulowano wniosek " + wnNumer);
				info += String.format("\r\n\r\nwn. nr <strong><b>%1$s</b></strong>\r\nnr inw.: %2$s \r\nnazwa: %3$s",
									                         r.get("wn_numer"),	 r.get("sdn_numer_inw"), r.get("sdn_nazwa"));
			}

			if (!info.isEmpty()){
				User.info("Anulowano: " + info);
			}

			lw.clearSelection();
			lw.resetTs();

		} catch (Exception e) {
			log.error(e.getMessage(), e);
			User.alert(e);

		}

	}




	public void generujDokumentyWybraneWnioski(){

		SqlDataSelectionsHandler lw = this.getPplSrodkiTrwaleWnioski();
		List<DataRow> selectedRows = lw.getSelectedRows();

		try(Connection conn = JdbcUtils.getConnection()){

			String info = "";

			for (DataRow r : selectedRows) {

				Object wnNumer = r.get("wn_numer");

				if (eq("T", r.get("wn_f_anulowany"))){
					User.alert("Brak możliwości generowania dokumentów dla wniosku '%1$s'. Wniosek ten został wcześniej anulowany.", wnNumer);
					continue;
				}

				if (!eq("T",r.get("wn_f_zatwierdzony"))){
					User.alert("Brak możliwości generowania dokumentów dla wniosku '%1$s'. Wniosek nie został zatwierdzony.", wnNumer);
					continue;
				}

				if (eq("T", r.get("wn_f_dok_wygenerowano"))){
					User.alert("Brak możliwości generowania dokumentów dla wniosku '%1$s'. Dla tego wniosku wygenerowano dokumenty.", wnNumer);
					continue;
				}


				String ret = JdbcUtils.sqlFnVarchar(conn, "PPADM.ST_WNIOSEK_GENERUJ_DOK",  r.get("wn_id"));

				if (ret!=null && !ret.startsWith("000000"))
					User.alert(r.get("wn_numer") + " -> " + ret);
				else {
					String dokNr = ""+JdbcUtils.sqlExecScalarQuery(conn, "select dok_id from kgt_dokumenty where dok_id = ? ", ret);
					info += String.format("\r\n\r\n<strong><b>dokument %1$s</b></strong>\r\nwn. nr: %2$s \r\nnr inw.: %3$s \r\nnazwa: %4$s",
												dokNr, 			r.get("wn_numer"),	 r.get("sdn_numer_inw"), r.get("sdn_nazwa"));
				}
			}

			if (!info.isEmpty()){
				User.info("Wygenerowano: " + info);
			}

			lw.clearSelection();
			lw.resetTs();

		} catch (Exception e) {
			log.error(e.getMessage(), e);
			User.alert(e);

		}

	}



	public void usunWybraneWnioski(){

		SqlDataSelectionsHandler lw = this.getPplSrodkiTrwaleWnioski();
		List<DataRow> selectedRows = lw.getSelectedRows();

		try(Connection conn = JdbcUtils.getConnection()){

			String info = "";
			for (DataRow r : selectedRows) {

				Object wnNumer = r.get("wn_numer");

				if (eq("T",r.get("wn_f_zatwierdzony"))){
					User.alert("Brak możliwości usunięcia wniosku '%1$s'. Wniosek ten został wcześniej zatwierdzony.", wnNumer);
					continue;
				}

				if (eq("T", r.get("wn_f_dok_wygenerowano"))){
					User.alert("Brak możliwości usunięcia wniosku '%1$s'. Dla tego wniosku wygenerowano dokumenty.", wnNumer);
					continue;
				}

				JdbcUtils.sqlExecNoQuery(conn, "delete stt_wnioski_parametry where wnp_id = ? ", r.get("wnp_id"));
				JdbcUtils.sqlExecNoQuery(conn, "delete stt_wnioski where wn_id = ? ", r.get("wn_id"));
				JdbcUtils.sqlExecNoQuery(conn, "delete stt_inwentaryzacje where i_id = ? ", r.get("wn_i_id"));

				info += String.format("\r\n\r\nwn. nr <strong><b>%1$s</b></strong>\r\nnr inw.: %2$s \r\nnazwa: %3$s",
						r.get("wn_numer"),	 r.get("sdn_numer_inw"), r.get("sdn_nazwa"));
			}

			if (!info.isEmpty()){
				User.info("Usunięto: " + info);
			}

			lw.clearSelection();
			lw.resetTs();

		} catch (Exception e) {
			log.error(e.getMessage(), e);
			User.alert(e);

		}

	}


}

src/main/java/com/comarch/egeria/pp/srodkiTrwale/SrodkiTrwaleBean.java
package com.comarch.egeria.pp.srodkiTrwale;

import com.comarch.egeria.pp.data.DataRow;
import com.comarch.egeria.pp.data.SessionBean;
import com.comarch.egeria.pp.data.SqlBean;
import com.comarch.egeria.pp.data.SqlDataSelectionsHandler;
import org.springframework.context.annotation.Scope;

import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

@Scope("view")
@Named
public class SrodkiTrwaleBean extends SqlBean implements Serializable {
	
	@Inject
    SessionBean sessionBean;

	String obecnaData = null;
	private SqlDataSelectionsHandler srTrwSlownik = null;

	public ArrayList<DataRow> getListaSrodkow() {
		if (this.srTrwSlownik == null) {
			this.setListaSrodkow(this.getLW("PPL_WSP_SRODKI_TRWALE", sessionBean.getPrc_id()));
		}
		return this.srTrwSlownik.getData();
	}
	
	public void setListaSrodkow(SqlDataSelectionsHandler srTrwSlownik) {
		this.srTrwSlownik = srTrwSlownik;
	}
	
	public String getDate() {
		DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
		Date date = new Date();
		this.obecnaData = dateFormat.format(date);
		return this.obecnaData;
	}

}

WebContent/faces/SrodkiTrwale/ListaSrodkowTrwalychPrc.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:cc="http://xmlns.jcp.org/jsf/composite/components">
<f:metadata>

</f:metadata>

<h:body>

	<ui:composition
		template="/WEB-INF/protectedElements/Templates/EgrTemplatePF70.xhtml">
		<ui:param name="submenuName" value="#{dic.LBL10001_nazwa_systemu}" />
		<ui:param name="formName" value="Lista środków trwałych" />

		<ui:define name="egr_content">

			<h:form id="frmNrth" styleClass="p5 pl20 pp-bg-lp-north-b-white-b-v">

				<cc:cLovButtonJS icon=""
								 styleClass="granatowy bsh1gray mr10"
								 value="Zmiana pracownika ..."
								 title="generuj wnioski o zmianę pracownika dla zaznaczonych wierszy (zmiana osoby odpowiedzialnej)"
								 lovDlgTitle="Wskaż pracownika:"
								 datasource="#{listaSrodkowTrwalychPrcBean.pplPracownicy}"
								 rowSelectedAction="#{listaSrodkowTrwalychPrcBean.generujWnioskiOZmianePracownika}"
								 update="frmCntr"
				/>

				<p:commandButton icon=""
								 styleClass="granatowy bsh1gray mr10"
								 value="Likwidacja ..." title="generuj wnioski o likwidację dla zaznaczonych wierszy"
								 action="#{listaSrodkowTrwalychPrcBean.generujWnioskiOLikwidacje}"
								 update="frmCntr"
								 onstart="hgon();"
								 oncomplete="hgoff();"
				/>

			</h:form>

			<h:form id="frmCntr" styleClass="bg-fff m20i p20 bsh2black flex-1">
				<cc:cLookupTableMultiselect
						datasource="#{listaSrodkowTrwalychPrcBean.pplSrodkiTrwale}"/>
			</h:form>

		</ui:define>
	</ui:composition>
</h:body>
</html>

WebContent/faces/SrodkiTrwale/ListaWnioskowStPrc.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:cc="http://xmlns.jcp.org/jsf/composite/components">
<f:metadata>

</f:metadata>

<h:body>

	<ui:composition
		template="/WEB-INF/protectedElements/Templates/EgrTemplatePF70.xhtml">
		<ui:param name="submenuName" value="#{dic.LBL10001_nazwa_systemu}" />
		<ui:param name="formName" value="Środki trwałe / lista wniosków" />

		<ui:define name="egr_content">

			<h:form id="frmNrth" styleClass="p5 pl20 pp-bg-lp-north-b-white-b-v">

				<p:commandButton icon="delete" styleClass="granatowy bsh1gray mr10"
								 value="Usuń" title="usuń wybrane wnioski (usunąć można tylko wnioski jeszcze niezatwierdzone lub anulowane)"
								 action="#{listaWnioskowStPrcBean.usunWybraneWnioski}"
								 update="frmCntr"
								 onstart="hgon();" oncomplete="hgoff();"
				/>

				<p:commandButton icon="clear" styleClass="granatowy bsh1gray mr10"
								 value="Anuluj"  title="anuluj wybrane wnioski (anulować można tylko wnioski jeszcze niezatwierdzone i nieanulowane)"
								 action="#{listaWnioskowStPrcBean.anulujWybraneWnioski}"
								 update="frmCntr"
								 onstart="hgon();" oncomplete="hgoff();"
				/>

				<p:commandButton icon="done" styleClass="granatowy bsh1gray mr10"
								 value="Zatwierdź" title="zatwierdź wybrane wnioski"
								 action="#{listaWnioskowStPrcBean.zatwierdzWybraneWnioski}"
								 update="frmCntr"
								 onstart="hgon();" oncomplete="hgoff();"
				/>

				<p:commandButton icon="done_all" styleClass="granatowy bsh1gray mr10"
								 value="Generuj dokumenty" title="generuj dokumenty dla wybranych wniosków"
								 action="#{listaWnioskowStPrcBean.generujDokumentyWybraneWnioski}"
								 update="frmCntr"
								 onstart="hgon();" oncomplete="hgoff();"
				/>

			</h:form>

			<h:form id="frmCntr" styleClass="bg-fff m20i p20 bsh2black flex-1">
				<cc:cLookupTableMultiselect
						datasource="#{listaWnioskowStPrcBean.pplSrodkiTrwaleWnioski}"/>
			</h:form>

		</ui:define>
	</ui:composition>
</h:body>
</html>

WebContent/faces/SrodkiTrwale/SrodkiTrwale.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://xmlns.jcp.org/jsf/composite/components">
<f:metadata>

</f:metadata>

<h:body>

	<ui:composition
		template="/WEB-INF/protectedElements/Templates/EgrTemplatePF70.xhtml">
		<ui:param name="submenuName" value="#{dic.LBL10001_nazwa_systemu}" />
		<ui:param name="formName" value="Lista środków trwałych" />

		<ui:define name="egr_content">

			<ui:include
				src="/WEB-INF/protectedElements/Wydruki/common/wydrukSrodkiTrwale.xhtml" />

			<h:form styleClass="pp-bg-lp-north-b-white-b-v p5 pl20 pr20">

				<p:commandButton value="drukuj" icon="print"
					style="min-width: 80px" styleClass="ctl-home-link-menu">
					<p:printer target="printContent1" />
				</p:commandButton>

			</h:form>

				<h:form styleClass="bg-fff m20i p20 flex-1">

					<c:cLookupTable
						datasource="#{srodkiTrwaleBean.getLW('PPL_WSP_SRODKI_TRWALE', sessionBean.prc_id)}"
						notActiveList="true"
					/>

				</h:form>

		</ui:define>

	</ui:composition>

</h:body>

</html>